name: PR Checkbox Handler

on:
  issue_comment:
    types: [edited]

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub Event Payload
        run: cat "$GITHUB_EVENT_PATH"

  update-title-on-checkbox:
    runs-on: ubuntu-latest
    if: >
      contains(github.event.comment.body, 'Click here to add `test-123`') &&
      contains(github.event.comment.body, '[x]') &&
      github.event.sender.login != 'github-actions[bot]'
    steps:
      - name: Checkout the specified branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Update PR title with test-123
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
        identifier="test-123"
        echo "Updating PR title with identifier: [$identifier]"
        current_title=$(gh pr view ${{ github.event.pull_request.number }} --json title -q ".title")

        if [[ "$current_title" != *$identifier* ]]; then
          new_title="$identifier: $current_title"
          echo "Changing PR title to: $new_title"
          gh pr edit ${{ github.event.pull_request.number }} --title "$new_title"
        else
          echo "No change needed"
        fi
