name: PR Checkbox Handler

on:
  issue_comment:
    types: [edited]

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub Event Payload
        run: cat "$GITHUB_EVENT_PATH"

  update-title-on-checkbox:
    runs-on: ubuntu-latest
    if: >
      contains(github.event.comment.body, 'Click here to add `test-123`') &&
      contains(github.event.comment.body, '[x]') &&
      github.event.sender.login != 'github-actions[bot]'
    steps:
      - name: Update PR title with test-123
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          identifier="test-123"
          echo "Updating PR title with identifier: [$identifier]"

          pr_number="${{ github.event.issue.number }}"
          echo "Using PR number: $pr_number"

          current_title=$(gh pr view "$pr_number" --repo "${{ github.repository }}" --json title -q ".title")
          echo "Current title: $current_title"

          if [[ "$current_title" != *$identifier* ]]; then
            new_title="$identifier: $current_title"
            echo "Changing PR title to: $new_title"
            gh pr edit "$pr_number" --repo "${{ github.repository }}" --title "$new_title"
          else
            echo "Title already contains the identifier. No change needed."
          fi
