name: PR Checkbox Handler

on:
  issue_comment:
    types: [edited]

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub Event Payload
      run: cat "$GITHUB_EVENT_PATH"

  update-title-on-checkbox:
    runs-on: ubuntu-latest
    if: >
      contains(github.event.comment.body, 'Click here to add `test-123`') &&
      contains(github.event.comment.body, '[x]') &&
      github.event.sender.login != 'github-actions[bot]'
    steps:
      - name: Update PR title with test-123
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # For issue_comment events on a PR, the pull request number is in the "issue" object.
          pr_number=$(jq -r '.issue.number' "$GITHUB_EVENT_PATH")
          current_title=$(gh pr view $pr_number --json title -q ".title")
          
          if [[ "$current_title" != test-123:* ]]; then
            new_title="test-123: $current_title"
            echo "Updating PR title to: $new_title"
            gh pr edit $pr_number --title "$new_title"
          else
            echo "Title is already prefixed. No change needed."
          fi
